global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:9090']
    metrics_path: '/metrics' 