server:
  port: 8080
  read_timeout: 15s
  write_timeout: 15s
  metrics_port: 9099

kafka:
  brokers: ["127.0.0.1:9092"]
  topic: "notifications.web"
  group_id: "notification-service"
  auto_offset_reset: "earliest"

websocket:
  read_buffer_size: 1024
  write_buffer_size: 1024
  pong_wait: 60s
  ping_period: 54s
  max_message_size: 512000

tls:
  enabled: false
  cert_file: "certs/server.crt"
  key_file: "certs/server.key" 